AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: Meraki Quotes API v2

Resources:
  AWSLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: AWSLambdaExecutionRole

  ExpressApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          SESSIONS_TABLE_NAME: ConappsSessions
          USERS_TABLE_NAME: ConappsUsers
          HELPERS_TABLE_NAME: ConappsHelpers
          MERAKI_QUOTES_TABLE_NAME: ConappsMerakiQuotes
          MERAKI_DEVICES_TABLE_NAME: ConappsMerakiDevices
      Policies: APIGatewayLambdaExecRole
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
