AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: Meraki Quotes API v2

Resources:
  AWSLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: AWSLambdaExecutionRole

  ExpressApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables:
          SESSIONS_TABLE_NAME: ConappsSessions
          USERS_TABLE_NAME: ConappsUsers
          HELPERS_TABLE_NAME: ConappsHelpers
          MERAKI_QUOTES_TABLE_NAME: ConappsMerakiQuotes
          MERAKI_DEVICES_TABLE_NAME: ConappsMerakiDevices
      Policies:
        -
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
        -
          Version: '2012-10-17'
          Statement:
          - Sid: '1'
            Effect: Allow
            Action:
            - apigateway:HEAD
            - apigateway:OPTIONS
            - apigateway:PATCH
            - apigateway:POST
            - apigateway:PUT
            - execute-api:*
            - logs:DescribeLogStreams
            - logs:GetLogEvents
            Resource:
            - arn:aws:apigateway:us-east-1::/restapis/n8cmrd4qu9/*
            - arn:aws:execute-api:us-east-1:925638840915:n8cmrd4qu9
            - arn:aws:execute-api:us-east-1:925638840915:n8cmrd4qu9/*
            - arn:aws:iam::925638840915:policy/CodeStar_meraki-quotes-a_Contributor
            - arn:aws:logs:us-east-1:925638840915:log-group:API-Gateway-Execution-Logs_n8cmrd4qu9/*
          - Sid: '2'
            Effect: Allow
            Action:
            - apigateway:GET
            - logs:DescribeLogGroups
            Resource:
            - "*"
        -
          Version: '2012-10-17'
          Statement:
          - Sid: ConappsDynamoDBReadWrite
            Effect: Allow
            Action:
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            Resource:
            - arn:aws:dynamodb:us-east-1:925638840915:table/ConappsMerakiDevices
            - arn:aws:dynamodb:us-east-1:925638840915:table/ConappsHelpers
            - arn:aws:dynamodb:us-east-1:925638840915:table/ConappsCounts
            - arn:aws:dynamodb:us-east-1:925638840915:table/ConappsUsers
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
